#!/usr/bin/env make
# Created by sebastientourbier on 2023-10-20
.DEFAULT_GOAL := help

# Define the project directory
PROJECT_DIR = $(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))

# Set environment variables for the docker image name and tag
IMAGE_NAME=ctp-anonymizer

TAG=1.0.0

$(info TAG = $(TAG))
# Replace +, /, _ with - to normalize the tag
# in case the tag includes a branch name
override TAG := $(subst +,-,$(TAG))
override TAG := $(subst /,-,$(TAG))
override TAG := $(subst _,-,$(TAG))
$(info TAG (Normalized) = $(TAG))

IMAGE_TAG=$(IMAGE_NAME):$(TAG)

# Define the build date and vcs reference
BUILD_DATE = $(shell date -u +"%Y-%m-%dT%H:%M:%SZ")
VCS_REF = $(shell git rev-parse --short HEAD)

#build-docker: @ Builds the Docker image
build-docker:
	docker build \
		-f docker/ctp-anonymizer/Dockerfile \
		-t $(IMAGE_TAG) \
		--build-arg BUILD_DATE=$(BUILD_DATE) \
		--build-arg VCS_REF=$(VCS_REF) \
		--build-arg VERSION=$(TAG) .

#install-python: @ Install the python package with pip
.PHONY: install-python
install-python:
	pip install -e .

#install-python-all: @ Install the python package with all dependencies used for development
.PHONY: install-python-all
install-python-all:
	pip install -e .[all]

#tests: @ Run all tests
.PHONY: tests
tests: build-docker clean-tests install-python-all
	@echo "Running pytest tests (PROJECT_DIR: $(PROJECT_DIR))..."
	pytest \
		--cov-config "$(PROJECT_DIR)/.coveragerc" \
		--cov-report html:"$(PROJECT_DIR)/tests/report/cov_html" \
		--cov-report xml:"$(PROJECT_DIR)/tests/report/cov.xml" \
		--cov-report lcov:"$(PROJECT_DIR)/tests/report/cov.info" \
		--cov=tml_ctp \
		-s \
		"${@}"

#clean-tests: @ Clean the directories generated by the pytest tests
.PHONY: clean-tests
clean-tests:
	rm -rf $(PROJECT_DIR)/tests/report
	rm -rf $(PROJECT_DIR)/tests/tmp

#help:	@ List available make command for this project
help:
	@grep -E '[a-zA-Z\.\-]+:.*?@ .*$$' $(MAKEFILE_LIST)| tr -d '#'  | awk 'BEGIN {FS = ":.*?@ "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
